export { LicenseWebpackPlugin } from './LicenseWebpackPlugin.js';
export { LicensePluginCore } from './LicensePluginCore.js';
export { viteLicensePlugin } from './ViteLicensePlugin.js';
export { normalizeLicense } from './checker/BuiltInLicenseChecker.js';
export type { LicensePluginOptions, OutputFormat, LicensePluginContext } from './LicensePluginCore.js';
export type { OutputFormat as WebpackOutputFormat } from './LicenseWebpackPlugin.js';
export type { PackageInfo } from './model/PackageInfo.js';
export type { LicenseInfo, OutputItem } from './model/LicenseInfo.js';
export type { LicenseBuildReport } from './model/LicenseBuildReport.js';
export type { Recorder } from './Recorder.js';
export { DefaultRecorder } from './Recorder.js';
export type { Policy, Preset, ComplianceStatus, ComplianceResult, ComplianceReport, LicenseSeverity } from './compliance/index.js';
export { evaluateLicense, evaluateUnknownLicense, evaluateMissingLicense, buildComplianceReport, resolvePolicy, getDefaultPolicy } from './compliance/index.js';
